# fly.toml app configuration file generated for loof-vpn on 2024-08-09T19:24:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loof-vpn'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
